# Stage 1: Build
# Using a newer Go version to fix stdlib vulnerabilities (CVE-2024-34156, etc.)
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY main.go .
# Compile the binary
RUN go build -o hello-devsecops main.go

# Stage 2: Production (Distroless)
# Remained secure with 0 vulnerabilities
FROM gcr.io/distroless/static-debian12
COPY --from=builder /app/hello-devsecops /
USER nonroot:nonroot
CMD ["/hello-devsecops"]
