# Stage 1: Build
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY main.go .
RUN go build -o hello-devsecops main.go

# Stage 2: Production (Distroless - brak shella, mniejszy attack surface)
FROM gcr.io/distroless/static-debian12
COPY --from=builder /app/hello-devsecops /
USER nonroot:nonroot
CMD ["/hello-devsecops"]
